version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  #AfterInstall:
     - location: afterinstall.sh
       timeout: 100
       runas: ubuntu
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
      runas: ubuntu
 
